{
 "title": "Dashboard1",
 "time": { "from": "2026-02-04T08:20:57.129Z", "to": "2026-02-08T08:20:57.129Z" },
 "panels": [
  {
   "title": "Temperature",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"farm_metrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |>last()"
    }
   ]
  },
  {
   "title": "Battery monitoring",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"farm_metrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"battery\")\n  |> group(columns: [\"_measurement\", \"_field\"])\n  |> top(n:1, columns:[\"_time\"])\n  |> last()"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"bucket1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"farm_metrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\n  |>last()"
    }
   ]
  }
 ]
}